mutation(
  $email: String!,
  $password: String!,
  $confirmPassword: String!,
) {
  createUser(input: {
    email: $email,
    password: $password,
    confirmPassword: $confirmPassword,
  }) {
    success
  }
}
