version: "3.2"

services:
  db:
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
  app:
    ports:
      - "8080:8080"
      - "4000:4000"
      - "9505:9505"
      - "9506:9506"
      - "35729:35729"
