language: node_js
sudo: false
branches:
  only:
    - master
node_js:
  - 10
  - 11
  - 12
  - 14
install:
  - make setup
script:
  - make test-all U_WEBSOCKETS_SKIP=true
notifications:
  email: false
