sudo: required
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.4"
language: node_js
node_js:
  - 4
  - 6
  - iojs
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - 'npm run cover'
after_success:
  - 'npm run cover:up'
notifications:
  email: false
