language: node_js
sudo: false
branches:
  only:
    - master
node_js:
  - 10
  - 11
  - 12
  - 14
install:
  - make setup
before_script:
  - npm i uNetworking/uWebSockets.js#v18.4.0
script:
  - make
notifications:
  email: false
