language: node_js
sudo: false
branches:
  only:
    - next
node_js:
  - 4
  - 6
  - 8
env:
  - PACKAGE=@grown/grown
before_script:
  - lerna bootstrap
script:
  - lerna run test --scope $PACKAGE
notifications:
  email: false
