sudo: required
dist: trusty
services:
  - postgresql
addons:
  postgresql: '9.5'
language: node_js
node_js:
  - 4
  - 6
  - 7
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - yarn add pg sqlite3
  - yarn build
script:
  - 'yarn test'
after_success:
  - 'yarn cover:up'
notifications:
  email: false
