version: "3.4"

services:
  db:
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
  web:
    ports:
      - "3000:3000"
      - "4000:4000"
      - "9505:9505"
      - "9506:9506"
      - "35729:35729"
  nginx:
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
