version: "3.4"

services:
  chrome:
    command: google-chrome --start-fullscreen http://web:9505/browser/connect
    image: martinsthiago/chrome:64.0.3282.186
  nginx:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.nginx
    image: grown-app/nginx
    #ports:
    #  - 80:80
    links:
     - web
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.web
    image: grown-app/web
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_NAME: ${DB_NAME:-user_dev}
      DB_PORT: ${DB_PORT:-5432}
      DB_HOST: ${DB_HOST:-db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-*secret*}
      WITHOUT_SEEDS: ${WITHOUT_SEEDS}
      REMOVE_LOG: ${REMOVE_LOG}
    #expose:
    #  - "8080"
    links:
      - db
  db:
    image: postgres:11
    volumes:
     - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DB_NAME:-user_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-*secret*}

networks:
  default:
    driver: bridge
