version: "3.4"

services:
  nginx:
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
  web:
    ports:
      - "1080:1080"
      - "1081:1081"
      - "1025:1025"
      - "3000:3000"
      - "9505:9505"
      - "9506:9506"
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    links:
      - db
  db:
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
