mutation(
  $token: String!,
  $newPassword: String!,
  $confirmPassword: String!,
) {
  resetPassword(input: {
    token: $oldPassword,
    newPassword: $newPassword,
    confirmPassword: $confirmPassword,
  }) {
    success
  }
}
