mutation(
  $oldPassword: String!,
  $newPassword: String!,
  $confirmPassword: String!,
) {
  updatePassword(input: {
    oldPassword: $oldPassword,
    newPassword: $newPassword,
    confirmPassword: $confirmPassword,
  }) {
    id
    email
  }
}
